### ISSUE TITLE
Error when applying model.compile(optimizer=Adam())

### ISSUE THREAD

**Issue by GireeshS22** [cyprienruffino/CTCModel#2]
Hi,

I am getting the following error when I execute the code *model.compile(optimizer=Adam())*

`model = CTCModel(input_data, y_pred)

model.compile(optimizer=Adam())
Traceback (most recent call last):

  File "<ipython-input-73-37948378bc01>", line 1, in <module>
    model.compile(optimizer=Adam())

  File "C:\Gireesh\Handwriting-CNN-LSTM\CTCModel.py", line 87, in compile
    self.outputs + [labels, input_length, label_length])

  File "C:\ProgramData\Anaconda3\envs\python36\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\python36\lib\site-packages\keras\layers\core.py", line 687, in call
    return self.function(inputs, **arguments)

  File "C:\Gireesh\Handwriting-CNN-LSTM\CTCModel.py", line 827, in ctc_loss_lambda_func
    y_pred, labels, input_length, label_length = args

  File "C:\ProgramData\Anaconda3\envs\python36\lib\site-packages\tensorflow\python\framework\ops.py", line 442, in __iter__
    "Tensor objects are only iterable when eager execution is "

TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.`

**Comment by juierror** [comment]
Probably, change 

model = CTCModel(input_data, y_pred)

to

model = CTCModel( [input_data], [y_pred])

**Comment by JohnLoveMm** [comment]
> Probably, change
> 
> model = CTCModel(input_data, y_pred)
> 
> to
> 
> model = CTCModel( [input_data], [y_pred])

do you know how to save model,and how to load a trained model?please help me

**Comment by cyprienruffino** [comment]
Hi ! Thanks @juierror for the answer :)
I updated the README to show how to save and load models.
Thanks for the reports !
